/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReserveRouteImport } from './routes/reserve'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FooterRouteImport } from './routes/footer'
import { Route as Drink_eat1RouteImport } from './routes/drink_eat1'
import { Route as DrinkEatRouteImport } from './routes/drink-eat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ReserveRoute = ReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterRoute = FooterRouteImport.update({
  id: '/footer',
  path: '/footer',
  getParentRoute: () => rootRouteImport,
} as any)
const Drink_eat1Route = Drink_eat1RouteImport.update({
  id: '/drink_eat1',
  path: '/drink_eat1',
  getParentRoute: () => rootRouteImport,
} as any)
const DrinkEatRoute = DrinkEatRouteImport.update({
  id: '/drink-eat',
  path: '/drink-eat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/drink-eat': typeof DrinkEatRoute
  '/drink_eat1': typeof Drink_eat1Route
  '/footer': typeof FooterRoute
  '/home': typeof HomeRoute
  '/reservation': typeof ReservationRoute
  '/reserve': typeof ReserveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/drink-eat': typeof DrinkEatRoute
  '/drink_eat1': typeof Drink_eat1Route
  '/footer': typeof FooterRoute
  '/home': typeof HomeRoute
  '/reservation': typeof ReservationRoute
  '/reserve': typeof ReserveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/drink-eat': typeof DrinkEatRoute
  '/drink_eat1': typeof Drink_eat1Route
  '/footer': typeof FooterRoute
  '/home': typeof HomeRoute
  '/reservation': typeof ReservationRoute
  '/reserve': typeof ReserveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/drink-eat'
    | '/drink_eat1'
    | '/footer'
    | '/home'
    | '/reservation'
    | '/reserve'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/drink-eat'
    | '/drink_eat1'
    | '/footer'
    | '/home'
    | '/reservation'
    | '/reserve'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/drink-eat'
    | '/drink_eat1'
    | '/footer'
    | '/home'
    | '/reservation'
    | '/reserve'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DrinkEatRoute: typeof DrinkEatRoute
  Drink_eat1Route: typeof Drink_eat1Route
  FooterRoute: typeof FooterRoute
  HomeRoute: typeof HomeRoute
  ReservationRoute: typeof ReservationRoute
  ReserveRoute: typeof ReserveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserve': {
      id: '/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof ReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer': {
      id: '/footer'
      path: '/footer'
      fullPath: '/footer'
      preLoaderRoute: typeof FooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink_eat1': {
      id: '/drink_eat1'
      path: '/drink_eat1'
      fullPath: '/drink_eat1'
      preLoaderRoute: typeof Drink_eat1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drink-eat': {
      id: '/drink-eat'
      path: '/drink-eat'
      fullPath: '/drink-eat'
      preLoaderRoute: typeof DrinkEatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DrinkEatRoute: DrinkEatRoute,
  Drink_eat1Route: Drink_eat1Route,
  FooterRoute: FooterRoute,
  HomeRoute: HomeRoute,
  ReservationRoute: ReservationRoute,
  ReserveRoute: ReserveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
